### ISSUE TITLE
Seeder for permissions 

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Auth#14]
seeder for default roles
- superadmin 
- course admin 
- instructor
- student 

Each package that define some roles/permissions should update this package as well

**Comment by qunabu** [comment]
https://github.com/EscolaLMS/API/blob/develop/database/seeds/DatabaseSeeder.php#L25

**Comment by pa-cholek** [comment]
The only permission currently used in Auth is 'user manage' created in RoleTableSeeder in Core package

**Comment by pa-cholek** [comment]
There is permission seeder in Auth now, but we still need to call it in API

**Comment by qunabu** [comment]
done ?
