### ISSUE TITLE
user params. saving consents 

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Auth#62]
example there are 3 consents to accept 
1 is mandatory 2 optional 
we should be able to save which user have accepted 
this model should be elastic

**Comment by qunabu** [comment]
it this something users `settings` is designed for ? 
![image](https://user-imag@pa-cholek ithubusercontent.com/214608/133557235-6a57030e-1813-4ca3-a2bb-91d19fb074ec.png)
@pa-cholek ?

**Comment by pa-cholek** [comment]
I have no idead what purpose settings serve, it was just something that was in Auth module before I started working on it.

**Comment by qunabu** [comment]
let discuss this on daily today

**Comment by qunabu** [comment]
we need some way to save some literal fields into user

**Comment by pa-cholek** [comment]
```php
            Route::get('/{id}/settings', [UserSettingsController::class, 'listUserSettings']);
            Route::patch('/{id}/settings', [UserSettingsController::class, 'patchUserSettings']);
            Route::put('/{id}/settings', [UserSettingsController::class, 'putUserSettings']);
```
using these methods you can add any settings to user by sending patch with 
```json
{
settings: [
{
key: 'string',
value: 'string'
}
]
}
```

**Comment by qunabu** [comment]
gr8, just add those for registration pliz
