### ISSUE TITLE
column `email` is not unique (in db) 

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Auth#66]
i think that `email` should be set as unique in database migration 

![image](https://user-images.githubusercontent.com/214608/133737744-afe4cebb-421b-42b2-a447-4d08f613bdf6.png)

```
        $user = $userService->createWithSettings($userSaveDto, $userSettingsDto);
```

allows to create multiple accounts under the same email

**Comment by pa-cholek** [comment]
https://github.com/EscolaLMS/Core/pull/22
